services:
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/app/openapi.yaml
    volumes:
      - ./api-specs/openapi.yaml:/app/openapi.yaml:ro
    # restart: unless-stopped

  swagger-editor:
    image: swaggerapi/swagger-editor:latest
    container_name: swagger-editor
    ports:
      - "8081:8080"
    volumes:
      - ./api-specs/openapi.yaml:/openapi.yaml:ro
    # restart: unless-stopped

  db:
      image: mongo:latest
      container_name: aethel-mongo-db
      ports:
        - "27017:27017"
      restart: unless-stopped
      volumes:
        - mongo_data:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
        # MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}

volumes:
  mongo_data:
