services:
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/app/openapi.yaml
      - BASE_URL=/swagger
    volumes:
      - ./openapi.yaml:/app/openapi.yaml:ro
    restart: unless-stopped

  swagger-editor:
    image: swaggerapi/swagger-editor:latest
    container_name: swagger-editor
    ports:
      - "8081:8080"
    volumes:
      - ./openapi.yaml:/openapi.yaml
    restart: unless-stopped
