[project]
name = "ai-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.12.3",
]

[dependency-groups]
dev = [
    "datamodel-code-generator>=0.35.0",
]
