name: Prettier Format Check

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write  
  pull-requests: write

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Prettier Action
        id: prettier
        uses: peter-evans/prettier-action@v2
        with:
          prettier-options: --write "**/*.{js,jsx,ts,tsx,json,md,yml,yaml}"
          commit-message: "chore: format code with Prettier"

      - name: Count formatted files
        id: count
        run: |
          FILES_CHANGED=$(git diff --name-only HEAD^ HEAD | wc -l || echo 0)
          echo "count=$FILES_CHANGED" >> $GITHUB_OUTPUT

      - name: Comment on PR
        if: always()
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.count.outputs.count == '0' && '✅ No files formatted.' || format('✨ {0} files formatted and committed back to the branch.', steps.count.outputs.count) }}
